project:
  type: website
  output-dir: docs
  
website:
  navbar:
    background: "#69727d"
    logo: images/MICS_logo-1.png
    left:
      - href: mattina.qmd
        text: Mattino
      - href: pomeriggio.qmd
        text: Pomeriggio
      - href: map.qmd
        text: Mappa Palazzo del Bo
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/company/mics-made-in-italy-circolare-e-sostenibile
      - icon: globe
        href: https://www.mics.tech/
  sidebar: false
  
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

