project:
  type: website
  output-dir: docs

website:
  title: "Verso il futuro del Made in Italy circolare e sostenibile:"
  navbar:
    left:
      - href: index.qmd
        text: Programma
      - href: map.qmd
        text: Mappa Palazzo del Bo

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

