---
title: "Programma Mattino"
subtitle: Aula Magna - Palazzo del Bo
format: html
sidebar: false
editor: visual
---

### 10:00 Accoglienza ospiti

### 10:30 Saluti istituzionali

### 10:45 MICS Made in Italy Circolare e Sostenibile

**Prof. [Marco Taisch](https://it.linkedin.com/in/marcotaisch)**, Presidente della Fondazione MICS

### 11:00 Sfide e prospettive dell'intelligenza artificiale

**Ing. [Marco Landi](https://www.linkedin.com/in/marco-landi-6bb8474/)**, Institut EuropIA e QuestIT

### 11:20 L’EU AI Act: cos’è e cosa prevede

**Dott. [Gabriele Mazzini](https://www.linkedin.com/in/gabriele-mazzini-2baa948/)**, Team leader AI Act, European Commission & MIT Fellow

### 11:40 Spoke 8: innovazioni digitali sostenibili e Intelligenza Artificiale per l'industria manifatturiera del Made in Italy

**Prof. [Daria Battini](https://www.linkedin.com/in/daria-battini-b7664011/)**, Università di Padova

### 11:55 Spoke 6: Produzione additiva per la Twin Transition

**Prof. [Federica Bondioli](https://www.linkedin.com/in/federica-bondioli-123002a/)**, Politecnico di Torino\
**Prof. [Enrico Savio](https://www.linkedin.com/in/enricosavio/)**, Università di Padova

### 12:10 Spoke 5: Fabbriche e processi a ciclo chiuso, sostenibili e inclusivi

**Prof. [Sergio Terzi](https://www.linkedin.com/in/sergioterzi/)**, Politecnico di Milano\
**Prof. [Fabrizio Dughiero](https://www.linkedin.com/in/fabrizio-dughiero-2b770721/)**, Università di Padova

### 12:25 Spoke 4: Materiali intelligenti e sostenibili per la circolarità

**Prof. [Domenico Caputo](https://www.linkedin.com/in/domenico-caputo-98867a2/)**, Università degli Studi di Napoli Federico II\
**Prof.ssa [Maria Cristina Lavagnolo](https://www.linkedin.com/in/maria-cristina-lavagnolo-1208397a/)**, Università di Padova

### 12:40 Spoke 3: Prodotti e materiali verdi e sostenibili

**Dott. [Pierluigi Barbaro](https://www.linkedin.com/in/pierluigi-barbaro-53540675/)**, CNR\
**Prof.ssa [Giulia Licini](https://www.linkedin.com/in/giulia-licini-0357589/)**, Università di Padova

### 12:55 Conclusioni finali

**Dott. [Fabrizio Cobis](https://www.linkedin.com/in/fabrizio-cobis-6a88ba12/)**, Ministero dell’Università e della Ricerca

### 13:00 – 14:30 Networking lunch in Basilica
