---
title: "Gli scarti industriali: recuperare risorse dai rifiuti"
subtitle: Aula Nievo, Palazzo del Bo
format: html
sidebar: false
editor: visual
toc: false
---

## PRIMA PARTE
### 14:45 Registrazione e accoglienza

### 15:00 Saluti iniziali
- Fabio Poles, Direttore Generale UniSMART, Fondazione Università di Padova

### 15:10 Introduzione al tema
**Il partenariato MICS per l’economia circolare in Italia: un modello per il futuro**

- Prof. Domenico Caputo, Università degli Studi di Napoli Federico II, Referente Spoke 4 , PE11, MICS Made in Italy Circolare e Sostenibile <br/>

**Scarti, rifiuti, sottoprodotti, End of Waste: definizioni e autorizzazioni**

-  Loris Tomiato, Direttore Generale dell’UO Economia Circolare e Ciclo dei Rifiuti, ARPA Veneto
- Stefania Tesser, Direttore Responsabile dell’UO Economia Circolare e Ciclo dei Rifiuti, ARPA Veneto

### 15:40 Tavola rotonda

- Michele Manica, Responsabile Ricerca e Sviluppo, Manica S.p.A.
- Claudia Florio, Responsabile Ricerca, Stazione Sperimentale per l’Industria delle Pelli e delle materie concianti
- Andrea Rambaldi, CEO, Fashionart Spa
- Roberto Pavin, CFO, Sirmax

Modera:

- Maria Cristina Lavagnolo, Coordinatrice CEWMS, Università degli Studi di Padova

## SECONDA PARTE
### 16:40 Tavoli di workshop

- Tavolo 1 - End of Waste e autorizzazioni
- Tavolo 2 - LCA, simbiosi industriale e altri strumenti decisionali
- Tavolo 3 - Tecnologie di Riciclo e recupero

### 18:00 Apertivo Networking

